### PR TITLE
Fix issue with auto-linking and class/module name clash.

### PR DESCRIPTION
**Pull request by joeced**
In version 0.21.1 we introduced handling for class/modules with this structure:

    module/
        module.m  # a class

However, auto-linking was not handled correctly

### CODE REVIEW

**Comment by joeced** [comment]
@rdzman I hope you have time to review this change, as it affects the auto-linking feature.

**Comment by itsmoosh** [comment]
This still breaks for my project with repeated directory names.

**Comment by rdzman** [comment]
It looks fine for my use cases. I ran it on a large project of mine that makes extensive use of auto-linking and it does not appear to have introduced any issues. The HTML output is identical to what it was before this PR.

But, I have not looked at the issue mentioned by @itsmoosh.

**Comment by itsmoosh** [comment]
Created PR #238 with my proposed fix. `short_names` cannot be used to replace items in `entities_table` when names of modules overlap with any other module, function, class, etc., because entries in `entities_table` will always be overwritten and this will always cause errors.

**Comment by joeced** [comment]
Thanks a lot @itsmoosh and @rdzman for testing and contributing to the project. Much appreciated.

**Pull request merged**
