### PR TITLE
[WIP] Further improvements to textmate based parser

### PR DESCRIPTION
**Pull request by apozharski**
Better classdef attributes and validator function parsing based on improvements to MATLAB-language-grammar in:
- https://github.com/mathworks/MATLAB-Language-grammar/pull/86
- https://github.com/mathworks/MATLAB-Language-grammar/pull/88
- https://github.com/mathworks/MATLAB-Language-grammar/pull/90

and a `textmate-grammar-python`  pr which bumps the MATLAB-language-grammar (which will be created once Mathworks pulls in the improvements).

Further improvements:
- parsing docstrings for functions

### CODE REVIEW

**Comment by joeced** [comment]
The tests, (see https://github.com/sphinx-contrib/matlabdomain/actions/runs/10058995696/job/27803269388?pr=258#step:4:106) are failing as `setup.py` does not require the textmate grammar package.

**Comment by apozharski** [comment]
Yep I have just been running `pytest` locally to get through the true errors. Unfortunately it looks like there are fundamental problems with the textmate grammar that I am not sure are solvable due to the limitations of the textmate grammar. In particular the syntax for multiline defaults is I believe unparseable. @watermarkhu I am unsure if you have any insights that I do not here.

An example of the problem:
```matlab
prop = [1;
              2;
              3]; % a prop
```
in which one cannot unambiguously identify which of the `;` actually ends the property default.

**Comment by joeced** [comment]
It's ok for the test to fail for now. We'll get there eventually. For the default value of properties the current code starts here: https://github.com/sphinx-contrib/matlabdomain/blob/b081e7c3473097ff41f4d9dc1f666cb6bdfebd3e/sphinxcontrib/mat_types.py#L1275 and uses more than 50 lines to collect it. I hope that textmate grammar can do it in less :)

**Comment by watermarkhu** [comment]
> Yep I have just been running `pytest` locally to get through the true errors. Unfortunately it looks like there are fundamental problems with the textmate grammar that I am not sure are solvable due to the limitations of the textmate grammar. In particular the syntax for multiline defaults is I believe unparseable. @watermarkhu I am unsure if you have any insights that I do not here.
> 
> An example of the problem:
> 
> ```matlab
> prop = [1;
>               2;
>               3]; % a prop
> ```
> 
> in which one cannot unambiguously identify which of the `;` actually ends the property default.

There are two ways to tackle this. 

1. **Further edits to the MATLAB grammar:** The MATLAB grammar can be further improved to catch these cases. In this case, we can add a dummy newline scope to the array and cell scopes. 

2. **Pre-parser:**. Similar to the current case, there is MATLAB's line continuations `...`, which is allowed to be inserted almost anywhere. I started on adding the line-continuation scope to places that I encountered them, but there are many, many more. 
    - https://github.com/mathworks/MATLAB-Language-grammar/pull/56
    - https://github.com/mathworks/MATLAB-Language-grammar/pull/69
    - https://github.com/mathworks/MATLAB-Language-grammar/pull/73

    Just for the sake of getting the tokens, I added a [pre-parser](https://github.com/watermarkhu/textmate-grammar-python/blob/96dd7144d7695187dc535b36d8924c952129264f/src/textmate_grammar/parsers/matlab/__init__.py#L51-L72) to simply remove line-continuations from the source file. While this method is far from ideal, it is another possibility.

**Comment by apozharski** [comment]
This is replaced with #261

**Pull request closed without merging**
